# Generated by Django 2.2.2 on 2019-06-05 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('extension', models.CharField(max_length=5, unique=True)),
                ('max_size', models.IntegerField()),
                ('info', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'file_types',
            },
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('file_url', models.CharField(max_length=1000)),
                ('file_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filemanager.FileTypeModel')),
            ],
            options={
                'db_table': 'files',
            },
        ),
        migrations.AddIndex(
            model_name='filemodel',
            index=models.Index(fields=['name', 'file_type'], name='file_index'),
        ),
    ]
