# Generated by Django 2.2.2 on 2019-06-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190605_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginmodel',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
