# Generated by Django 2.2.2 on 2019-06-05 00:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(max_length=250)),
                ('content', models.CharField(max_length=1500)),
                ('parent', models.BigIntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.PostModel')),
            ],
            options={
                'db_table': 'comments',
            },
            managers=[
                ('manag', django.db.models.manager.Manager()),
            ],
        ),
    ]
